# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ridgeline < Formula
  desc "Self-hosted intelligence platform for indie developers"
  homepage "https://github.com/xydac/ridgeline"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xydac/ridgeline/releases/download/v0.1.0/ridgeline_0.1.0_darwin_amd64.tar.gz"
      sha256 "472de6f52cec6b8af2015458f134abf9ef39a86516dbd57fcdb3414e87061c5e"

      define_method(:install) do
        bin.install "ridgeline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xydac/ridgeline/releases/download/v0.1.0/ridgeline_0.1.0_darwin_arm64.tar.gz"
      sha256 "e4816828eb36ab5c605a2b6cf4d0dc2c27d94ba3214e784abf3e263d576c3780"

      define_method(:install) do
        bin.install "ridgeline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xydac/ridgeline/releases/download/v0.1.0/ridgeline_0.1.0_linux_amd64.tar.gz"
      sha256 "e9421c98550d8c4eb35e468400977b4719b43240c64e594909aa6d63775f3a83"
      define_method(:install) do
        bin.install "ridgeline"
      end
    end
  end

  test do
    system "#{bin}/ridgeline", "version"
  end
end
