# This file was generated by GoReleaser. DO NOT EDIT.
cask "ridgeline" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "8ba6f4277df9a97594a71af40347f0a2242fca6664ae3f1c354310ebd882d93b"
      url "https://github.com/xydac/ridgeline/releases/download/v#{version}/ridgeline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a997e289fa6e45d6181ecf01963d5b74741a9aa61bd4a48806bd7024ec7f94e2"
      url "https://github.com/xydac/ridgeline/releases/download/v#{version}/ridgeline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5229358ec8359ac84ec33c65edd3af9e1d632c00eec4b3f18374fa7175cd4c60"
      url "https://github.com/xydac/ridgeline/releases/download/v#{version}/ridgeline_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ridgeline"
  desc "Self-hosted intelligence platform for indie developers"
  homepage "https://github.com/xydac/ridgeline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ridgeline"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ridgeline"]
    end
  end

  # No zap stanza required

end
