# This file was generated by GoReleaser. DO NOT EDIT.
cask "ridgeline" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "3817b10b1bb83d059c9c8d539a3d3a56804b6a2efad06e7e69a68a898a0ddce8"
      url "https://github.com/xydac/ridgeline/releases/download/v#{version}/ridgeline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "70975dc3e90aca7fe3f11552e3146e787e0487ac476f61ac9cd8491355bd17a9"
      url "https://github.com/xydac/ridgeline/releases/download/v#{version}/ridgeline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2f331e8b77fa903bb71be75a425aa387596057c5dc7ab89bcf8fb13598e65745"
      url "https://github.com/xydac/ridgeline/releases/download/v#{version}/ridgeline_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ridgeline"
  desc "Self-hosted intelligence platform for indie developers"
  homepage "https://github.com/xydac/ridgeline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ridgeline"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ridgeline"]
    end
  end

  # No zap stanza required

end
