# This file was generated by GoReleaser. DO NOT EDIT.
cask "ridgeline" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "8a52d8bd0d5a2546ff4361808539872c2aaa38ab7b4131fbe043e519b226c63d"
      url "https://github.com/xydac/ridgeline/releases/download/v#{version}/ridgeline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e67ad759cea3a661a313bf9125cfdd1c47817c26d73424e5a444e7c4f715c105"
      url "https://github.com/xydac/ridgeline/releases/download/v#{version}/ridgeline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "24dfce5cd101ef19be7c271a021ee3237fac07bfa1e26973d7202f053990a23c"
      url "https://github.com/xydac/ridgeline/releases/download/v#{version}/ridgeline_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ridgeline"
  desc "Self-hosted intelligence platform for indie developers"
  homepage "https://github.com/xydac/ridgeline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ridgeline"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ridgeline"]
    end
  end

  # No zap stanza required

end
